[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
testpaths = tests apps
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --strict-markers
    --cov=apps
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=90
markers =
    integration: marks tests as integration tests
